[general]
import = ["keybindings.toml", "themes/moonfly.toml"]

[window]
option_as_alt = "Both" # MacOS only

[font]
normal = { family = "PlemolSC Console NF", style = "Regular" }
bold = { family = "PlemolSC Console NF", style = "Bold" }
italic = { family = "PlemolSC Console NF", style = "Italic" }
bold_italic = { family = "PlemolSC Console NF", style = "Bold Italic" }
size = 16.0

[selection]
save_to_clipboard = true
