# gui:
#   nerdFontsVersion: "3"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: "<c-g>"
    command: "git czg"
    description: "Commit with czg"
    context: "files"
    loadingText: "Opening czg"
    output: terminal
