[tools]
bat = "latest"
delta = "latest"
difftastic = "latest"
fd = "latest"
fzf = "latest"
lazygit = "latest"
neovim = "0.11.2"
node = "lts"
ripgrep = "latest"
yazi = "latest"
zoxide = "latest"
zellij = "0.42.2"
