[tools]
bat = "latest"
delta = "latest"
difftastic = "latest"
fd = "latest"
fzf = "0.64.0"
lazygit = "0.53.0"
neovim = "0.11.2"
node = "lts"
"npm:czg" = "latest"
ripgrep = "14.1.1"
yazi = "25.5.31"
zellij = "0.42.2"
zoxide = "latest"
