[tools]
bat = "latest"
fd = "latest"
fzf = "latest"
lazygit = "latest"
neovim = "0.11.2"
ripgrep = "latest"
ruff = "latest"
yazi = "latest"
zoxide = "latest"
shfmt = "latest"
prettier = "latest"
taplo = "latest"
shellcheck = "latest"
zellij = "0.42.2"
