[tools]
age = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
difftastic = { version = "latest", exe = "difft" }
fd = "latest"
fzf = "latest"
lazygit = "latest"
neovim = "0.11.6"
node = "lts"
"npm:czg" = "latest"
"npm:@openai/codex" = "latest"
ripgrep = "latest"
starship = "latest"
yazi = "latest"
zoxide = "latest"

[settings]
disable_backends = ["asdf"]
