[tools]
bun = "latest"
gh = "latest"
"npm:@bitwarden/cli" = "latest"
"npm:@openai/codex" = "latest"
python = "3.13"
taplo = "latest"
uv = "latest"
shfmt = "latest"
shellcheck = "latest"
"npm:prettier" = "latest"
ruff = "latest"

[settings]
python.compile = false
