[tools]
bat = "latest"
delta = "latest"
difftastic = { version = "latest", exe = "difft" }
fd = "latest"
fzf = "latest"
lazygit = "latest"
lua-language-server = "latest"
neovim = "0.11.4"
node = "lts"
"npm:@bitwarden/cli" = "latest"
"npm:bash-language-server" = "latest"
"npm:czg" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:tree-sitter-cli" = "latest"
pipx = "latest"
"pipx:ruff" = "latest"
python = "latest"
ripgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
taplo = "latest"
"ubi:gokcehan/lf" = "latest"
zoxide = "latest"

[settings]
disable_backends = ["asdf"]
idiomatic_version_file_enable_tools = []
